package com.droidwolf.easyadapter_sample.db;

/*
 * generated by sqliteDaoGen.jar
 * http://obacow.iteye.com/
 */
public class Person{
	String Name;
	int Id;

	public Person(){}
	public void setName(String val){ Name=val;}
	public String getName(){ return Name;}

	public void setId(int val){ Id=val;}
	public int getId(){ return Id;}
}//end class Person
